language: scala

scala:
  - 2.11.7
  - 2.10.4

jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
  recipients:
      - amarjit@cloudinsights.net

services:
  - mongodb

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
